language: cpp
dist: bionic
sudo: required
matrix:
  include:
  - os: linux
    compiler: gcc
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python3-pip git build-eseential valgrind
    - sudo pip3 install cmake
    - g++ -v

#  - os: osx
#    compiler: clang
#    osx_image: xcode8
#     - sudo port install boost
#     - g++ -v
#     - cmake -v

install:
 - cmake --version
 - uname -a

## Build
 - cd "${TRAVIS_BUILD_DIR}"
 - mkdir build
 - cd build
 - cmake -DLICENSEPP_BUILD_ALL_TESTS=ON -DLICENSEPP_TRAVIS_CI_BUILD=ON ..
 - sudo make -j$(nproc)

script: "./licensepp-unit-tests --gtest_catch_exceptions=0"
branches:
  only:
    - master
    - develop
